# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a1b285b98bf7520530f11ded74975cea8e9f6fa1f965a5a02a6f0c542b3be04376a106373fca5937d1dc7d9d204db9af00a419195819a863d3f6f90c12f49e64

test:
  secret_key_base: f516a338f880832e352d5ab3e9344350a4915322728e1b380578bc9867799ffaff18d1d083af74467e594c2794c119cc5d9b0b8e60e6f4531417d32c27285b89

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
